---
- name: Web Servers Uptimes
  hosts: webservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime

- name: WAS Servers Uptimes
  hosts: wasservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime

- name: DB Servers Uptimes
  hosts: dbservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime
