---
- name: Web Servers Uptimes
  hosts: webservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime
    register: uptime

  - name : print uptime
    debug:
      var: uptime.stdout

- name: WAS Servers Uptimes
  hosts: wasservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime
    register: uptime

  - name : print uptime
    debug:
      var: uptime.stdout

- name: DB Servers Uptimes
  hosts: dbservers
  remote_user: root

  tasks:
  - name: execute uptime
    shell: uptime
    register: uptime

  - name : print uptime
    debug:
      var: uptime.stdout
