---
- name: Web Servers Execute Script
  hosts: webservers
  remote_user: root

  tasks:
  - name: chmod script file
    command: chmod +x /root/script.sh

  - name: execute script file
    shell: sh /root/script.sh
    register: sh_result

  - name: chmod script file
    command: chmod -x /root/script.sh

  - name: print sh result
    debug:
      msg: "{{ sh_result.stdout_lines }}"

- name: WAS Servers Execute Script
  hosts: wasservers
  remote_user: root

  tasks:
  - name: chmod script file
    command: chmod +x /root/script.sh

  - name: execute script file
    shell: sh /root/script.sh
    register: sh_result

  - name: chmod script file
    command: chmod -x /root/script.sh

  - name: print sh result
    debug:
      msg: "{{ sh_result.stdout_lines }}"

- name: DB Servers Execute Script
  hosts: dbservers
  remote_user: root

  tasks:
  - name: chmod script file
    command: chmod +x /root/script.sh

  - name: execute script file
    shell: sh /root/script.sh
    register: sh_result

  - name: chmod script file
    command: chmod -x /root/script.sh

  - name: print sh result
    debug:
      msg: "{{ sh_result.stdout_lines }}"
